# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/66ff361b-b708-47a7-8e7c-1b83fd93f0a8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices = {
    "root" = {
      device = "/dev/disk/by-uuid/4a2f39ab-e802-4a90-b685-2a072b0d58d1";
    };
    "swap" = {
      device = "/dev/disk/by-uuid/b6f89b41-450c-464d-b241-1261d49150bf";
    };
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A257-547E";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b6f89b41-450c-464d-b241-1261d49150bf"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
