# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.rtl88x2bu
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4ef277a6-9628-43e0-bb24-74accf47312a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."env-pv".device = "/dev/disk/by-uuid/525bb864-f80f-4aad-81e0-6c5f3f693831";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7573-45E5";
      fsType = "vfat";
    };

  # fileSystems."/media/share" =
  #   { device = "192.168.0.65:/media/external-drive";
  #     fsType = "nfs";
  #   };
  # fileSystems."/media/drive2" =
  #   { device = "192.168.0.65:/media/drive2";
  #     fsType = "nfs";
  #   };

  swapDevices = [ { device = "/swapfile"; size = 2048; priority = 4; } ];

  nix.maxJobs = lib.mkDefault 24;
  # High-DPI console
  console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
