{ pkgs, ... }:

let
  lib = pkgs.lib;
  git-change-author = pkgs.writeShellScript "git-change-author" (builtins.readFile ./change-author.sh);
  scripts = import ./scripts.nix { inherit pkgs; };
in
{
  home.packages = with pkgs; [
    any-nix-shell
    asciinema
    bat
    cabal2nix
    cabal-install
    cachix
    cgdb
    choose
    chromium
    coreutils
    dateutils
    diskonaut
    duf
    dua
    editorconfig-core-c
    evince
    exa
    expect
    fd
    file
    fira
    fira-code
    font-awesome
    ghc
    gimp
    git-crypt
    gitAndTools.hub
    gnome.devhelp
    gnomeExtensions.system-monitor
    gnumake
    gnupg
    gotop
    helix
    htop
    htop
    imagemagick
    inkscape
    jq
    killall
    libreoffice
    # libreoffice-fresh
    libsecret
    lshw
    macchina
    mosh
    mpv
    neofetch
    niv
    nix-bundle
    nix-index
    nix-output-monitor
    nix-prefetch-git
    nix-prefetch-github
    nnn
    nnn
    obsidian
    pciutils
    pidgin
    prismlauncher
    q-text-as-data
    remarshal
    retroarchFull
    ripgrep
    scripts.copy
    scripts.vpn
    sd
    shotwell
    signal-desktop
    spot
    spotify
    stdenv
    tmux
    transmission-gtk
    tree
    tree
    tup
    usbutils
    vault
    vlc
    wl-clipboard
    xclip
  ] ++ (with gitAndTools; [
    gh
    git-absorb
    # git-change-author
    git-gone
    git-open
    git-recent
    git-standup
    git-test
    git-fame
    scripts.git-weekend
    steam
  ]);
}
